### ISSUE TITLE
Remove support of old netmhc version dependent on Python 2.x

### ISSUE THREAD

**Issue by jonasscheid** [KohlbacherLab/epytope#36]
I recently recognized, that some NetMHC Family tools (e.g. NetMHC <= 3.4) run with python2 scripts. Since Epytope runs python3 the execution of this external software runs into py2 vs py3 syntax conflicts. Should we remove support of all py2 based predictors?

**Comment by b-schubert** [comment]
But isnt this just an issue of NetMHC configuration? If you specify the correct python version for NetMHC they should work no?

Would keep them if possible for backward compatibility...
