### ISSUE TITLE
NetMHCIIpan 3.1 class is missing crucial methods

### ISSUE THREAD

**Issue by jonasscheid** [KohlbacherLab/epytope#37]
[NetMHCIIpan 3.1 class](https://github.com/jonasscheid/epytope/blob/5f5accea2a98dc8496f9d03cc99de65deb1850fb/epytope/EpitopePrediction/External.py#L3990) in `EpitopePrediction/External.py` is missing crucial methods like `parse_external_result`. It cannot be used. Since NetMHCIIpan 3.0 is covered by Epytope I would propose to remove this class and optionally add the newer Version NetMHCIIpan 4.0 to Epytope.

**Comment by christopher-mohr** [comment]
Hi @jonasscheid, I think it should be fine since the class inherits from [NetMHCIIpan 3.0](https://github.com/jonasscheid/epytope/blob/5f5accea2a98dc8496f9d03cc99de65deb1850fb/epytope/EpitopePrediction/External.py#L2103). I guess the output formats of these methods are identical.
