### ISSUE TITLE
Current Class2 external tools don't predict CombinedAlleles

### ISSUE THREAD

**Issue by jonasscheid** [KohlbacherLab/epytope#45]
When I am trying to predict peptides with e.g. `NetMHCIIpan 3.0` with a `CombinedAllele` like `'HLA-DPA1*01:03-HLA-DPB1*01:01'` the output states, that the allele is not supported. However it is supported and you can observe it in the [supported_alleles](https://github.com/KohlbacherLab/epytope/blob/65fd57a77a4ad5a35e9b1f2e5ddb242ae3ccd05f/epytope/EpitopePrediction/External.py#L2254). When I change `'HLA-DPA1*01:03-HLA-DPB1*01:01'` to `'HLA-DPA1*01:03-DPB1*01:01'` in the `supported_alleles` it works. So I guess all the listed `CombinedAlleles` have an obsolete `HLA-` string in front of the beta chain

My input looked as follows in a Jupiter notebook:

```
peptides = [Peptide("SYFPEITHIFIASFS"),Peptide("FIASNGVKLSYFPEI")]
alleles = [Allele("HLA-DRB1*01:01"), Allele("HLA-DRB1*01:03"), CombinedAllele("HLA-DPA1*01:03-HLA-DPB1*01:01")]
predictor = EpitopePredictorFactory("netmhcIIpan", version="3.0")
results = predictor.predict(peptides, alleles=alleles, command='.path/to/netMHCIIpan-3.0/netMHCIIpan')
```

**Comment by christopher-mohr** [comment]
Ok let's remove the second `HLA` in the list of available alleles in the corresponding tool classes. If you call create  a `CombinedAllele` object with `HLA-DPA1*01:03-HLA-DPB1*01:01` and `HLA-DPA1*01:03-DPB1*01:01`, do both initializations work?

**Comment by jonasscheid** [comment]
Yes!
