### ISSUE TITLE
Should HLA typing remain a part of FRED?

### ISSUE THREAD

**Issue by lkuchenb** [KohlbacherLab/epytope#8]
I wonder whether HLA typing is really something you would just want to call as a function from Python code. It's a lengthy analysis and Pipelines exist in Nextflow (https://github.com/nf-core/hlatyping) and Snakemake (https://github.com/lkuchenb/MultiHLA).

Any opinions on this?

**Comment by christopher-mohr** [comment]
Would it be a lot of effort to keep the existing interfaces for HLA typing? I guess there might still be cases in which someone would like to build "pure Python" pipelines/scripts. However, personally I'm fine with not keeping it as part of FRED.

**Comment by christopher-mohr** [comment]
Decision postponed due to missing feedback.

**Comment by christopher-mohr** [comment]
We will keep it in there for now.
